#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Save initial contents of version.json
previousVersionJson=$(cat docs/version.json)

# Update version.json with the latest commit hash
latestHash=$(git log -n 1 dev --pretty=format:%H)
if ! node tools/set-github-pages-version.js "$latestHash"; then
  exit 1
fi

# Check if the version file changed. If it did, we need to commit the change to the gh-pages branch
currentVersionJson=$(cat docs/version.json)
if [ "$previousVersionJson" != "$currentVersionJson" ]; then
	echo "Not equal!"
	echo "$previousVersionJson"
	echo "$currentVersionJson"
fi
