#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Needed to find tsc
PATH=$PATH:node_modules/.bin

# Check for unused dependencies
node tools/check-unused-dependencies.js

# Check for linter errors
if ! eslint "src/*" "test/" --ext js,ts,jsx,tsx; then
  exit 1
fi

# Compile
if ! tsc; then
	exit 1
fi

# Run tests
if ! jest; then
  exit 1
fi
